### ISSUE TITLE
Better exception prompt for ExistingVersionError

### ISSUE THREAD

**Issue by 42thcoder** [bundler/gemstash#117] opened 2016-11-11 06:14 UTC
Sometimes I mistake to push samge gem with same version twice, and I got `<h1>Internal Server Error</h1>` in the console.

Maybe we can improve it and prompt cli a better message.

Tell me if I can help~

**Comment by olleolleolle** [comment] 2017-03-11 16:48
@42thcoder Thank you very much for your report!

This report is a duplicate of #99. Can we close this issue?

**Closed** 2018-10-04 00:36 UTC
Labels: duplicate
